2020-10-14 17:48:02,871 INFO: Application Startup [in /Users/wesleydavis/Desktop/dungeons_unlimited/app/__init__.py:75]
2020-10-14 17:48:15,821 ERROR: Exception on /auth/password_reset_request [POST] [in /Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/app/auth/routes.py", line 66, in password_reset_request
    password_reset_email(user)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/app/auth/email.py", line 6, in password_reset_email
    token = user.get_reset_password_token()
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/app/models/auth/user.py", line 58, in get_reset_password_token
    return jwt.endcode(
AttributeError: module 'jwt' has no attribute 'endcode'
2020-10-14 17:50:33,997 INFO: Application Startup [in /Users/wesleydavis/Desktop/dungeons_unlimited/app/__init__.py:75]
2020-10-14 17:50:47,237 ERROR: Exception on /auth/password_reset_request [POST] [in /Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/app/auth/routes.py", line 66, in password_reset_request
    password_reset_email(user)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/app/auth/email.py", line 9, in password_reset_email
    sender=current_app.config['AMDMINS'][0],
KeyError: 'AMDMINS'
2020-10-14 17:53:04,896 INFO: Application Startup [in /Users/wesleydavis/Desktop/dungeons_unlimited/app/__init__.py:75]
2020-10-14 17:53:09,506 ERROR: Exception on /auth/password_reset_request [POST] [in /Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/app/auth/routes.py", line 66, in password_reset_request
    password_reset_email(user)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/app/auth/email.py", line 17, in password_reset_email
    user=user, token=token))
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/app/auth/templates/reset_password_message.html", line 9, in top-level template code
    <p>{{ url_for('auth.reset_password', token=token, _external=True) }}</p>
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/wesleydavis/Desktop/dungeons_unlimited/dun_un_venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth.reset_password' with values ['token']. Did you mean 'auth.password_reset' instead?
2020-10-14 17:55:32,611 INFO: Application Startup [in /Users/wesleydavis/Desktop/dungeons_unlimited/app/__init__.py:75]
2020-10-14 17:56:09,041 INFO: Application Startup [in /Users/wesleydavis/Desktop/dungeons_unlimited/app/__init__.py:76]
2020-10-14 18:00:16,614 INFO: Application Startup [in /Users/wesleydavis/Desktop/dungeons_unlimited/app/__init__.py:76]
2020-10-14 18:01:23,325 INFO: Application Startup [in /Users/wesleydavis/Desktop/dungeons_unlimited/app/__init__.py:76]
